spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(afmOhnWo8N/U0A+WJSmUKgmuuFvlW9W4rTnbi2VfTN4OflW/ZF8rPDkvjMyud/uOatPAzf8FUDBQx7wJqAkZw98mD74hSwZZqpLvrCxq+Za1LJeqQ9eGDLIWZf5xVCcF)
    username: ENC(EfBTdf5UCACGLxdmaHt9Fg==)
    password: ENC(x03YhhuKzc9a2uQoqZ7dcc/UiK/N0fyk)

  jpa:
    hibernate:
      show-sql: true
      properties:
        hibernate.format_sql: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  port: 8080

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: jasypt_key

springdoc:
  version: v1.0.0
  swagger-ui:
    path: /swagger-glowing.html
    tagsSorter: alpha
    operationsSorter: alpha
